(global-linum-mode)
(xterm-mouse-mode 1)
(global-whitespace-mode 1)
(setq-default indent-tabs-mode nil)
(show-paren-mode 1)
(load-theme 'wombat)
(desktop-save-mode 1)
(setq column-number-mode t)
(setq scroll-step 1)
(split-window-right)
(set-face-attribute 'default nil :height 170)
(setq whitespace-line-column 250)
(require 'auto-complete)
(setq ac-auto-start 4)
(put 'downcase-region 'disabled nil)

(global-set-key (kbd "M-p") 'project-explorer-open)
(set-language-environment "UTF-8")
(set-default-coding-systems 'utf-8)

(add-hook 'before-save-hook 'delete-trailing-whitespace)
