(setenv "PATH" (concat "/usr/local/bin:" (getenv "PATH") ":" (getenv "HOME") "/go/bin/"))
(setq exec-path (split-string (getenv "PATH") ":"))
(add-to-list 'load-path "~/devbox/external/go-mode.el/")
(add-to-list 'load-path "~/devbox/external/goflymake/")
(add-to-list 'load-path "~/go/bin/")
(add-to-list 'load-path "~/.emacs.d/elisp/external")
(autoload 'go-mode "go-mode" nil t)
(add-to-list 'auto-mode-alist '("\\.go\\'" . go-mode))
(setq gofmt-command "goimports")
(add-hook 'before-save-hook 'gofmt-before-save)
(add-hook 'go-mode-hook 'lsp-deferred)
(add-hook 'completion-at-point-functions 'go-complete-at-point)
(setenv "GOPATH" "/Users/alandelaney/go/bin/")
(require 'go-flymake)
;;(require 'go-flycheck)
(require 'protobuf-mode)
(eval-after-load 'flycheck
  '(add-hook 'flycheck-mode-hook #'flycheck-golangci-lint-setup))
(require 'lsp-mode)
(add-hook 'go-mode-hook #'lsp-deferred)
(defun lsp-go-install-save-hooks ()
  (add-hook 'before-save-hook #'lsp-format-buffer t t)
  (add-hook 'before-save-hook #'lsp-organize-imports t t))
(add-hook 'go-mode-hook #'lsp-go-install-save-hooks)
